// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3SWRuu3Y5v-MC4saOILpeXLsFiVbcEGc',
    appId: '1:683504612347:android:40e9dfcd1fcd9e6d97115e',
    messagingSenderId: '683504612347',
    projectId: 'eimunisasi-81ae1',
    databaseURL: 'https://eimunisasi-81ae1.firebaseio.com',
    storageBucket: 'eimunisasi-81ae1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz7GFyMLiRAEi3jzap-Gm0wio8Lv6WKNQ',
    appId: '1:683504612347:ios:49d9cf52e55340e397115e',
    messagingSenderId: '683504612347',
    projectId: 'eimunisasi-81ae1',
    databaseURL: 'https://eimunisasi-81ae1.firebaseio.com',
    storageBucket: 'eimunisasi-81ae1.appspot.com',
    androidClientId: '683504612347-3eph1h0vnqn430qqtukc6v71o45k06t9.apps.googleusercontent.com',
    iosClientId: '683504612347-ot8n5ld4d2eglr31sf9aev5ciggmt7t8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eimunisasiNakes',
  );

}