class Constant {
  static const List<String> listTypeOfVaccine = [
    'Engerix-B',
    'Vaksin Polio 10 dosis (b-opv)',
    'BCG Vaccine',
    'BCG Vaccine SSI',
    'Vaksin BCG Kering DTP-HB-Hib',
    'Vaksin DTP (DTP Vaccine',
    'Vaksin DTP-HB 5',
    'Vaksin DTP-HB 10',
    'Vaksin Jerap TD',
    'Pentabio',
    'PCV10',
    'Synflorix',
    'PCV13',
    'Prevnar',
    'RotaTeq (RV5)',
    'Rotarix (RV1)',
    'Vaksin trivalent (Flubio, Vaxigrip)',
    'quadrivalent (FluQuadri)',
    'M-M-R II',
    'Vaksin Ixivaro',
    'JEspect',
    'ImoJev',
    'Varicella',
    'Varilrix',
    'Varivax',
    'AVAXIM 160',
    'TYPHIM Vi',
  ];
}
